### PR TITLE
Implemented side bar section in all pages

### PR DESCRIPTION
**Pull request by tmccoy529**
Added the sidebarsection component to the prototype and updated all pages that were using the side bar. This was to handle bug 15135: Contact Us H2 Footer Spacing and Font Size in TFS

### CODE REVIEW

**Review by sgrg1 — DISMISSED** [review]
looks good to me

**Review by martypowell — APPROVED** [review]

**Review by martypowell — CHANGES_REQUESTED** [review]
@tmccoy529 I think this is still pointing locally, so well need to merge the sidebar component first.

**Comment by martypowell** [comment]
@tmccoy529 putting on hold until we get feedback from @sdurphy

**Comment by martypowell** [comment]
@tmccoy529 took this off hold, can you update components and make sure this is still valid?

**Review by martypowell — APPROVED** [review]

**Pull request merged**
