### PR TITLE
Adjusted Bootstrap classes assigned to card containers.

### PR DESCRIPTION
**Pull request by theilman7**
Addresses Bug [15186](https://oittfs.bcg.ad.bcgov.us/BAUCollection/BaltimoreCounty.Gov%20Website/_workitems/edit/15186). Replaced the Bootstrap responsive utilities associated with the container in the demo.

### CODE REVIEW

**Review by martypowell — CHANGES_REQUESTED** [review]
@theilman7 code looks good, but I think maybe we want to keep the two columsn for a bit longer, checkout the cards around 800px or just when the page goes to one column (in general)

image

**Comment by martypowell** [comment]
> @theilman7 code looks good, but I think maybe we want to keep the two columsn for a bit longer, checkout the cards around 800px or just when the page goes to one column (in general)
> 
> image

@sdurphy do we have an absolute max-width we would want cards to be?

**Comment by theilman7** [comment]
Doing a "better or worse" type thing with my most recent push. Added a `col-sm-6` to the first card set as a test, to bridge the gap you were referring to. Let me know if this looks better when you pull the branch down @martypowell

**Comment by martypowell** [comment]
> Doing a "better or worse" type thing with my most recent push. Added a `col-sm-6` to the first card set as a test, to bridge the gap you were referring to. Let me know if this looks better when you pull the branch down @martypowell

@theilman7 can you have sam come over and checkout the options please?

**Comment by theilman7** [comment]
@martypowell Had @sdurphy come over and give the ok (aka rubber stamp) for my example. I have updated the Bootstrap styles to the remaining examples on the page. He can do an official test once the update has been merged so he can view the link.

**Review by martypowell — APPROVED** [review]
This looks great to me.

**Comment by martypowell** [comment]
completing on behalf of @theilman7 as he not available for a couple of days.

**Pull request merged**
